/*
Erro quando vaid adicionar no mes 2
 */
package projetojava;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author emanoel
 */
public class AgendaStart extends javax.swing.JFrame {
    
    DefaultListModel lista = new DefaultListModel();
    private int mes = 12;
    private int dia = 31;
    private int horas = 8;
    private String matrizes[][][] = new String[mes][dia][horas];
    private int data[] = new int[3];
    Agenda agendas = new Agenda();
    
    public AgendaStart() {
        initComponents();
        agendas.mostrarMatriz(matrizes,lista);
        //System.out.print(Arrays.toString(dataCompromisso()));
    }
    public int[] dataCompromisso(){
        int mes = Integer.parseInt(txtMes.getValue().toString());
        int dia = Integer.parseInt(txtDia.getValue().toString());
        int horas = Integer.parseInt(txtHoras.getValue().toString());
        data[0] = mes;
        data[1] = dia;
        data[2] = horas;
        return data;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        islAgenda = new javax.swing.JList<>();
        btnMostrarMatriz = new javax.swing.JButton();
        btnAddCompromisso = new javax.swing.JButton();
        btnObtcompromisso = new javax.swing.JButton();
        lblString = new javax.swing.JTextField();
        txtMes = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDia = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txtHoras = new javax.swing.JSpinner();
        btnRemoverCompromisso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        islAgenda.setModel(lista);
        islAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                islAgendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(islAgenda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 235, 783, 318));

        btnMostrarMatriz.setText("MostrarMatriz");
        btnMostrarMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMatrizActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarMatriz, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 12, -1, -1));

        btnAddCompromisso.setText("AdicionarCompromisso");
        btnAddCompromisso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCompromissoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCompromisso, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 90, -1, -1));

        btnObtcompromisso.setText("ObtarCompromisso");
        btnObtcompromisso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtcompromissoActionPerformed(evt);
            }
        });
        getContentPane().add(btnObtcompromisso, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 90, -1, -1));
        getContentPane().add(lblString, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 190, 393, -1));
        getContentPane().add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 137, 62, -1));

        jLabel1.setText("Mes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 142, -1, -1));

        jLabel2.setText("Dia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 142, -1, -1));
        getContentPane().add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 137, 62, -1));

        jLabel3.setText("Horas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 142, -1, -1));
        getContentPane().add(txtHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 137, 62, -1));

        btnRemoverCompromisso.setText("RemoverCompromisso");
        btnRemoverCompromisso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverCompromissoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoverCompromisso, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 12, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void islAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_islAgendaMouseClicked
        //JOptionPane.showMessageDialog(null,"ERRO! Não pode adicionar clicando");
    }//GEN-LAST:event_islAgendaMouseClicked

    private void btnMostrarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMatrizActionPerformed
        // TODO add your handling code here:
        agendas.mostrarMatriz(matrizes,lista);
    }//GEN-LAST:event_btnMostrarMatrizActionPerformed

    private void btnObtcompromissoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtcompromissoActionPerformed
        // TODO add your handling code here:
        int datas[] = dataCompromisso();
        agendas.obtarCompromisso(datas[0],datas[1],datas[2],matrizes,lista); //mes, dia, horas, matrizes, lista);
    }                                                 

    private void btnAddCompromissoActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        int datas[] = dataCompromisso();
        String mensagem = lblString.getText();
        agendas.adicionarCompromisso(matrizes, datas[0],datas[1],datas[2], mensagem, lista);
    }//GEN-LAST:event_btnObtcompromissoActionPerformed
/*
    private void btnAddCompromissoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCompromissoActionPerformed
        // TODO add your handling code her
        
    }//GEN-LAST:event_btnAddCompromissoActionPerformed
*/
    private void btnRemoverCompromissoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverCompromissoActionPerformed
        // TODO add your handling code here:
        int datas[] = dataCompromisso();
        agendas.removerCompromisso(datas[0],datas[1],datas[2], matrizes, lista);
    }//GEN-LAST:event_btnRemoverCompromissoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaStart().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCompromisso;
    private javax.swing.JButton btnMostrarMatriz;
    private javax.swing.JButton btnObtcompromisso;
    private javax.swing.JButton btnRemoverCompromisso;
    private javax.swing.JList<String> islAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblString;
    private javax.swing.JSpinner txtDia;
    private javax.swing.JSpinner txtHoras;
    private javax.swing.JSpinner txtMes;
    // End of variables declaration//GEN-END:variables
}
